#!/bin/sh

registry_testhost='
{ "ServerURL": "testhost.example.com",
  "Username": "hello",
  "Secret": "world"
}
'
registry_testtoken='
{ "ServerURL": "testtoken.example.com",
  "Username": "<token>",
  "Secret": "deadbeefcafe"
}
'

if [ "$1" = "get" ]; then
  read hostname
  case "$hostname" in
    testhost.example.com)
      echo "${registry_testhost}"
      exit 0
      ;;
    testtoken.example.com)
      echo "${registry_testtoken}"
      exit 0
      ;;
  esac
fi
# unhandled request
exit 1
