name: CI - Registry

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      RELEASE_GO_VER: "1.26"

    steps:
    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: "Set up Go ${{ env.RELEASE_GO_VER }}"
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: "${{ env.RELEASE_GO_VER }}"
        check-latest: true
      id: go

    - name: Build
      run: make binaries

    - name: Registry - Distribution
      run: make ci-distribution

    - name: Registry - Zot
      run: make ci-zot
